services:
  mirs:
    build: . # Dockerfileの位置を指定する
    container_name: ros2_humble_for_mirs250x
    network_mode: host
    ipc: host
    privileged: true # USBやGPUの使用許可
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=90
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/tmp/.Xauthority:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input:/dev/input
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    stdin_open: true
    tty: true # terminalの割当
    command: bash
