services:
  mirs:
    build: . # Dockerfileの位置を指定する
    container_name: ros2_humble_for_mirs
    privileged: true #すべての権限付与（本番環境では使わない）
    network_mode: host
    ipc: host
    pid: host

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=90

    volumes:
      - ./src:/root/projects/mirsws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-dev/null}:${XAUTHORITY}:ro

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 #LiDAR
      - /dev/ttyUSB1:/dev/ttyUSB1 #ESP32
      - /dev/input/js0:/dev/input/js0 #joystick

    stdin_open: true
    tty: true # terminalの割当
    command: bash
