crawler_teleop_node:
  ros__parameters:
    axis_left: 1   # Left stick vertical (2nd)
    axis_right: 3  # Right stick vertical (4th)
    scale_linear: 0.5
    scale_angular: 1.0
    enable_button: 5  # L1 (10th)
